Wizardry/Core/HelpBox/Source/HelpBoxHack.c

fix issue: https://github.com/MokhaLeee/fe8u-cskillsys-kernel/issues/6

fix helpbox issue #6

---

Contants/Texts/Source/texts/Skills_BattleStatus.txt
Data/SkillSys/SkillInfo.c
Wizardry/Core/BattleSys/Source/PreBattleCalc.c
include/constants/skills.enum.txt

Inflict the poison status on your opponent during combat.

Skill - PoisonPoint

---

Wizardry/Core/BattleSys/Source/PreBattleCalc.c

This should implement the otimization we talked about in the thread, and reduce the number of SkillTester call by quite a good number
I tried to respect the existing identation, wich was already inconstistant with the real depths of code block

Added AuraSkill optimization by Refactoring

---

Contants/Texts/Source/texts/Skills_StatusGetter.txt
Data/SkillSys/SkillInfo.c
Wizardry/Core/UnitStatusGetter/source/MovGetter.c
include/constants/skills.enum.txt

+1 movement per turn up to a maximum of 6 turns.

Skill - SpeedBoost

---

Contants/Texts/Source/texts/Skills_BattleStatus.txt
Data/SkillSys/SkillInfo.c
Wizardry/Core/BattleSys/Source/PreBattleCalc.c
include/constants/skills.person.enum.txt

If your opponent's speed is 4 or greater than yours, +10 ATK, otherwise if 1-3 greater then +5 ATK.

Skill - Analytic

---

Contants/Texts/Source/texts/Skills_PrePhase.txt
Data/SkillSys/SkillInfo.c
Wizardry/Core/SkillSys/MiscSkillEffects/PrePhaseSkills/PrePhaseHeal.c
include/constants/skills.person.enum.txt

Heal 15% HP at the start of the turn if it is raining.

Skill - RainDish

---

Contants/Texts/Source/texts/Skills_BattleStatus.txt
Data/SkillSys/SkillInfo.c
Wizardry/Core/BattleSys/Source/PreBattleCalc.c
include/constants/skills.person.enum.txt

If it is raining, double this unit's battle speed.

Skill - SwiftSwim

---

Contants/Texts/Source/texts/Skills_BattleStatus.txt
Data/SkillSys/SkillInfo.c
Wizardry/Core/BattleSys/Source/PreBattleCalc.c
include/constants/skills.person.enum.txt

If there is a sandstorm, double this unit's battle speed.

Skill - SandRush

---

Contants/Texts/Source/texts/Skills_BattleStatus.txt
Data/SkillSys/SkillInfo.c
Wizardry/Core/BattleSys/Source/PreBattleCalc.c
include/constants/skills.person.enum.txt

If it is snowing, double this unit's battle speed.

Skill - SlushRush

---

Contants/Texts/Source/texts/Skills_BattleStatus.txt
Data/SkillSys/SkillInfo.c
Wizardry/Core/BattleSys/Source/PreBattleCalc.c
include/constants/skills.person.enum.txt

If it is sunny, double this unit's battle speed.

Skill - Chlorophyll

---

Wizardry/Core/BattleSys/Source/BattleHit.c
docs/BattleSystem.md

result = ([atk + correction - def]) * (100% + increase%) * (200%  + crit_correction%) / (100% + decrease%) + real_damage

Rewrite battle damage

---

Contants/Texts/Source/texts/Skills_Menu.txt
Data/SkillSys/SkillActionInfo.c
Data/SkillSys/SkillExtraInfo.c
Data/SkillSys/SkillInfo.c
Data/SkillSys/SkillMenuInfo.c
Wizardry/Core/SkillSys/MiscSkillEffects/MenuSkills/Mine.c
Wizardry/Core/SkillSys/MiscSkillEffects/MiscSkillEffects.event
include/constants/skills-others.enum.txt
include/skill-system.h

Made a unit skill for Mine to go alongside the LightRune.

Skill - Mine

---

Contants/Texts/Source/texts/Skills_BattleAct.txt
Data/SkillSys/SkillAnimInfo.c
Data/SkillSys/SkillInfo.c
Wizardry/Core/BattleSys/Source/BattleHit.c
include/constants/skills-others.enum.txt

When attacking, ignore 25% of enemy defense.

Skill - LunarBrace

---

Contants/Texts/Source/texts/Skills_PostAction.txt
Data/SkillSys/SkillExtraInfo.c
Data/SkillSys/SkillInfo.c
Wizardry/Common/PostActionHook/data.event
Wizardry/Core/SkillSys/MiscSkillEffects/MiscSkillEffects.event
Wizardry/Core/SkillSys/MiscSkillEffects/PostActionSkills/GetItem.c
include/constants/skills-others.enum.txt

Get 100 gold after killing an enemy.

Skill - GoldDigger

---

Contants/Texts/Source/texts/Skills_BattleOrder.txt
Data/SkillSys/SkillAnimInfo.c
Data/SkillSys/SkillInfo.c
Wizardry/Core/BattleSys/Source/BattleOrder.c
include/constants/skills-equip.enum.txt

Vantage if the defender is at full HP.

Skill - GaleWings

---

Contants/Texts/Source/texts/Skills_BattleStatus.txt
Data/SkillSys/SkillInfo.c
Wizardry/Core/BattleSys/Source/BattleCalcReal.c
include/constants/skills-others.enum.txt

+50 crit if the skill holder's HP is less than or equal to 50%.

Skill - FranticSwing

---

Contants/Texts/Source/texts/Skills_Misc.txt
Data/SkillSys/SkillInfo.c
Wizardry/Common/BwlRework/source/BwlSupport.c
include/constants/skills-others.enum.txt

Unit gains support points at twice the usual rate.

Skill - SocialButterfly

---

Contants/Texts/Source/texts/SkillSys.txt
Contants/Texts/Source/texts/Skills_Menu.txt
Data/SkillSys/SkillActionInfo.c
Data/SkillSys/SkillExtraInfo.c
Data/SkillSys/SkillInfo.c
Data/SkillSys/SkillMenuInfo.c
Wizardry/Core/SkillSys/MiscSkillEffects/MenuSkills/Repair.c
Wizardry/Core/SkillSys/MiscSkillEffects/MiscSkillEffects.event
include/constants/skills-others.enum.txt
include/skill-system.h

This is a fun one I thought of. 
This turns a unit into a miniture blacksmith that can restore their equipped weapon to full uses in exchange for 1000 gold so long as it is under B rank.
As a trade off, it can restore ``Prf`` weapons as well.

Skill - Blacksmith

---

Data/SkillSys/SkillExtraInfo.c
Wizardry/Core/SkillSys/MiscSkillEffects/MenuSkills/Repair.c

Took the gold amount out of ``SkilExtraInfo.c`` and moved it back into ``Repair.c``

Moved the gold amount to Repair.c

---

Contants/Texts/Source/texts/Skills_Menu.txt
Data/SkillSys/SkillActionInfo.c
Data/SkillSys/SkillInfo.c
Data/SkillSys/SkillMenuInfo.c
Wizardry/Core/SkillSys/MiscSkillEffects/MenuSkills/Swarp.c
Wizardry/Core/SkillSys/MiscSkillEffects/MiscSkillEffects.event
include/constants/skills-equip.enum.txt
include/skill-system.h

I've started to get back into porting the existing skills. 
Skill effect: Swap the skill holder and an ally unit using rescue's range.

Skill - Swarp

---

.clang-format
.github/workflows/build.yml
Tools/scripts/lynjump-detector.sh
makefile

Brief:
Automatically setup envirment and exec DEBUG BUILD
todo task:
1. apply auto RELEASE BUILD
2. apply auto clang detection

NEW: Add CI build for cskillsys

---

Tools/scripts/lynjump-detector.sh

At present, the same generic error message is output to the console in all three cases for this script. 
This PR updates the messages to be more informative for the user.

Updated Lyn detector messages

---

Data/BattleSys/WeaponHpCost.c
Data/BattleSys/WeaponHpDrain.c
Data/Data.event
Debug/Event/Source/debug-event.c
Patches/PATCH_WeaponHpCostConfig.txt
Patches/PATCH_WeaponHpDrainConfig.txt
Preload/Reloc.event
Wizardry/Core/BattleSys/BattleSys.event
Wizardry/Core/BattleSys/EfxResireWeapon/EfxResireWeapon.event
Wizardry/Core/BattleSys/EfxResireWeapon/Source/EfxResireWeapon.c
Wizardry/Core/BattleSys/HpCost/Source/HpCost.c
Wizardry/Core/BattleSys/RoundAnim/Source/BanimRound.c
Wizardry/Core/BattleSys/Source/BattleHitAttr.c
Wizardry/Core/ComboAttack/Source/battle-order-combo.c
docs/SystemConfig.md
include/Configs/config-debug.h
include/Configs/config-memmap.s
include/Configs/configs.h
include/battle-system.h

1. Auto detect EfxResire for weapon for banim parse.
2. Add modular weapon hp drain config
3. Add modular weapon hp cost config

Update hp-drain & hp-cost process
